### PR TITLE
Added printing of stats to screen

### PR DESCRIPTION
**Pull request by sbernauer**
Hi,
i've redone my first pull request to match some naming conventions and to use the new custom fonts feature.
This PR adds printing of fps, server load, Network and Pixel-stats to the screen.
The only problem are the missing background color of the text, this actually looks kind of weird (see image).
It would be nice, if you could add an background color to the text or give an hint what's in your opinion the best way to do this.
Screenshot

### CODE REVIEW

**Comment by TobleMiner** [comment]
I like the idea. I'll have to do some testing regarding performance impact though since the additional write for the pixel counter basically doubles the overall amount of data written.
I'll definitely add solid backgrounds for text. Just didn't get around to doing it yet.

**Comment by sbernauer** [comment]
Thanks for your fast reply!
I expected an small decrease of performance, but i thought that the cache would work better (no random access), but of course the memory address must be shared across all cores on an NUMA-node.
I've done some basic testing and didn't see that much of a difference. But the test isn't ideal (run an on laptop, ...), so i suggest further investigation.
On the other side we could only count the bytes received and approximate the pixel/s.

My test:
```
for i in $(seq 1 10); do
	./shoreline -f vnc -l 12 & sleep 2; ../sturmflut/sturmflut 127.0.0.1 ../sturmflut/cat.jpg -t 24 & sleep 10; bmon -b -p lo -o ascii:quitafter=3 | tail -n 1 | awk '{ print $2 }'; killall sturmflut; killall shoreline
	sleep 3
done
```

The performance-tests run in the following order. The tests did run directly after each other.
1.) Code before my commit
2.) Code after my commit
3.) And again code before my commit
4.) And again code after my commit

Screenshot_20191119_211106

**Comment by TobleMiner** [comment]
Wow, thanks for the extensive test!

Unfortunately it needs to be tested on a NUMA-enabled system to get meaningful results. Think I'll make it a compile-time flag and estimate the number of pixels from network throughput if disabled.

**Comment by TobleMiner** [comment]
Implemented through 8eb04b36a0443cebc3222ba7d199864ddf635845 and 25fff6d4052e3bb93e9ab615d32169ed3ab8c340 . I chose a little different approach adding a new component to shoreline, thus I'll have to leave this unmerged. Sorry for that and for taking such a long time to get around to actually implementing it. Hope this is ok for you.

**Comment by sbernauer** [comment]
Hi Tobias,

gut Ding will Weile haben ;) Thanks for your nice solution, it is 1000 times more elegant than my solution. I've tested the performance of your new solution and i'm quite shocked:
With feature STATISTICS enabled:  11.04Gb/s
With feature STATISTICS disabled: 34.08Gb/s

I think the difference is that significant, that you should mention it in the section performance at your README. I can create an Merge Request if you like.

I used to separate servers to don't mess up the measurements with the client on the same server.
Each server has 2 x "Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz", in total 20 core / 40 threads and 8 memory channels. Link is 100G :)
Commands used:
[server] ./shoreline -f vnc -t arial.ttf -l 40
[client] for i in $(seq 100); do ./sturmflut fe80::37%enp4s0 cat.jpg -t 1 & done

A big shout out to you for creating this very well designed piece of software that gets quite complicated with time!

**Comment by TobleMiner** [comment]
Ah, sorry. That's probably mostly due to the feature PIXEL_COUNT. Guess I should just disable that option by default and rely on the pixel count estimation mode. Thanks

**Pull request closed without merging**
